import * as Joi from 'joi';

Joi.calendardate().cast('date');
Joi.calendardate().cast('days');
Joi.calendardate().cast('format');
Joi.calendardate().cast('months');
Joi.calendardate().cast('number');
Joi.calendardate().cast('quarters');
Joi.calendardate().cast('weeks');
Joi.calendardate().cast('years');
Joi.calendardate().eq('today');
Joi.calendardate().eq(new Date());
Joi.calendardate().eq(Joi.ref('date'));
Joi.calendardate().format((value) => [0, 0, 0]);
Joi.calendardate().format((value) => new Date());
Joi.calendardate().format('YYYY-MM-DD');
Joi.calendardate().future();
Joi.calendardate().future({});
Joi.calendardate().future({exact: [1, 'day']});
Joi.calendardate().future({less: [1, 'week']});
Joi.calendardate().future({more: [1, 'month']});
Joi.calendardate().future({exact: [1, 'quarter'], less: [1, 'year']});
Joi.calendardate().future({exact: [1, 'd'], more: [1, 'w']});
Joi.calendardate().future({less: [1, 'M'], more: [1, 'Q']});
Joi.calendardate().future({exact: [1, 'y'], less: [1, 'days'], more: [1, 'weeks']});
Joi.calendardate().ge('today');
Joi.calendardate().ge(new Date());
Joi.calendardate().ge(Joi.ref('date'));
Joi.calendardate().gt('2021-06-28');
Joi.calendardate().gt(new Date());
Joi.calendardate().gt(Joi.ref('date'));
Joi.calendardate().gt('2021-06-28', {});
Joi.calendardate().gt('2021-06-28', {exact: '1 month', less: '1 month', more: '1 month'});
Joi.calendardate().le('today');
Joi.calendardate().le(new Date());
Joi.calendardate().le(Joi.ref('date'));
Joi.calendardate().lt('2021-06-28');
Joi.calendardate().lt(new Date());
Joi.calendardate().lt(Joi.ref('date'));
Joi.calendardate().lt('2021-06-28', {});
Joi.calendardate().lt('2021-06-28', {exact: '1 month', less: '1 month', more: '1 month'});
Joi.calendardate().past();
Joi.calendardate().past({});
Joi.calendardate().past({exact: '1 month', less: '1 month', more: '1 month'});
Joi.calendardate().trim();
Joi.calendardate().trim(true);
